// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApyxMEmxniH78onsrcXRJE9PNiXwuT1no',
    appId: '1:407997731128:web:b1220da8262e5fbe5c71cd',
    messagingSenderId: '407997731128',
    projectId: 'pharmaplus-67ed4',
    authDomain: 'pharmaplus-67ed4.firebaseapp.com',
    storageBucket: 'pharmaplus-67ed4.firebasestorage.app',
    measurementId: 'G-K40G27JSQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUDm-I4Olu05dzBpjKX81SUTcLH4MDSyk',
    appId: '1:407997731128:android:f1e9d5697fb82dd45c71cd',
    messagingSenderId: '407997731128',
    projectId: 'pharmaplus-67ed4',
    storageBucket: 'pharmaplus-67ed4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU9nZiGnJvUikZ5Bi-bEUyLdph2_i4u3U',
    appId: '1:407997731128:ios:9e6fb325e23d5fda5c71cd',
    messagingSenderId: '407997731128',
    projectId: 'pharmaplus-67ed4',
    storageBucket: 'pharmaplus-67ed4.firebasestorage.app',
    iosBundleId: 'com.example.pharmaplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU9nZiGnJvUikZ5Bi-bEUyLdph2_i4u3U',
    appId: '1:407997731128:ios:9e6fb325e23d5fda5c71cd',
    messagingSenderId: '407997731128',
    projectId: 'pharmaplus-67ed4',
    storageBucket: 'pharmaplus-67ed4.firebasestorage.app',
    iosBundleId: 'com.example.pharmaplus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApyxMEmxniH78onsrcXRJE9PNiXwuT1no',
    appId: '1:407997731128:web:2c5bd7f4612cd4255c71cd',
    messagingSenderId: '407997731128',
    projectId: 'pharmaplus-67ed4',
    authDomain: 'pharmaplus-67ed4.firebaseapp.com',
    storageBucket: 'pharmaplus-67ed4.firebasestorage.app',
    measurementId: 'G-2GT0NRGZCM',
  );
}
